name: Test

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  check_release_updates:
    name: Check Release Updates
    runs-on: ubuntu-latest
    outputs:
      IS_UPDATED: ${{ steps.check_release_updates.outputs.IS_UPDATED }}
      LATEST_JETBRAINS_RELEASE_TAG: ${{ steps.check_release_updates.outputs.LATEST_JETBRAINS_RELEASE_TAG }}
      LATEST_MAPLE_RELEASE_TAG: ${{ steps.check_release_updates.outputs.LATEST_MAPLE_RELEASE_TAG }}

    steps:
      - name: Check Release Updates
        id: check_release_updates
        run: |
          PREV_JETBRAINS_RELEASE_TAG=$(cat jetbrains_release_tag.txt 2>/dev/null || echo "")
          PREV_MAPLE_RELEASE_TAG=$(cat maple_release_tag.txt 2>/dev/null || echo "")
          LATEST_JETBRAINS_RELEASE_TAG=$(curl -s https://api.github.com/repos/JetBrains/JetBrainsMono/releases/latest | jq -r '.tag_name')
          LATEST_MAPLE_RELEASE_TAG=$(curl -s https://api.github.com/repos/subframe7536/maple-font/releases/latest | jq -r '.tag_name')

          echo "$LATEST_JETBRAINS_RELEASE_TAG" > jetbrains_release_tag.txt
          echo "$LATEST_MAPLE_RELEASE_TAG" > maple_release_tag.txt
          echo "IS_UPDATED=true" >> $GITHUB_OUTPUT
          echo "LATEST_JETBRAINS_RELEASE_TAG=$LATEST_JETBRAINS_RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "LATEST_MAPLE_RELEASE_TAG=$LATEST_MAPLE_RELEASE_TAG" >> $GITHUB_OUTPUT

  fuse_release_fonts:
    name: Fuse Release Fonts
    runs-on: ubuntu-latest
    needs: check_release_updates
    if: ${{ needs.check_release_updates.outputs.IS_UPDATED }} == 'true'
    strategy:
      fail-fast: false
      matrix:
        NERD:
          - SUFFIX: -NF
            ARGS: --nerd-font
          - SUFFIX: ""
            ARGS: --no-nerd-font
        NARROW:
          - SUFFIX: -NR
            ARGS: --cn-narrow
          - SUFFIX: ""
            ARGS: ""
    env:
      LATEST_MAPLE_RELEASE_TAG: ${{ needs.check_release_updates.outputs.LATEST_MAPLE_RELEASE_TAG }}
      NERD_SUFFIX: ${{ matrix.NERD.SUFFIX }}
      NERD_ARGS: ${{ matrix.NERD.ARGS }}
      NARROW_ARGS: ${{ matrix.NARROW.ARGS }}

    steps:
      - name: Install Pip Dependencies
        run: pip install gftools fonttools

      - name: Build Maple
        run: |
          # git clone -b "$LATEST_MAPLE_RELEASE_TAG" --single-branch https://github.com/subframe7536/maple-font.git
          git clone https://github.com/subframe7536/maple-font.git
          cd maple-font
          pip install -r requirements.txt
          python build.py --normal --liga --cn --hinted --ttf-only $NERD_ARGS $NARROW_ARGS
          cd ..
